# Ensure system hostname matches inventory entry
# todo: Check idempotency and only change if necessary
# todo: Add advices for naming guidelines if needed
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when:
    - inventory_hostname != ansible_facts.hostname
    - ansible_facts.os_family == "Debian"
